---
- hosts: centos
  vars:
    apache_listen_port: 81
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
  tasks:
    # - debug:
    #     msg: "apache_listen_port: {{ apache_listen_port }}"
    # - debug:
    #     msg: "ntp_servers: {{ ntp_servers }}"
    # - name: include apache role
    #   include_role:
    #     name: geerlingguy.apache
    - name: include ntp role
      include_role:
        name: ntp
